<<<<<<< HEAD
# Generated by Django 5.1.3 on 2024-11-10 19:11
=======
# Generated by Django 5.1.3 on 2024-11-10 15:43
>>>>>>> 47d5486 (:wrench: build: obtendo os dados dos filmes e criando app Movies)

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('title', models.CharField(max_length=300)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('overview', models.CharField(max_length=300)),
                ('genres', models.CharField(max_length=300)),
                ('runtime', models.IntegerField()),
                ('similar_movies', models.CharField(max_length=500)),
=======
                ('movie_name', models.CharField(max_length=255, unique=True)),
                ('similar_movies', models.TextField(blank=True, null=True)),
>>>>>>> 47d5486 (:wrench: build: obtendo os dados dos filmes e criando app Movies)
            ],
        ),
    ]
