# Generated by Django 5.1.3 on 2024-11-10 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('overview', models.CharField(max_length=300)),
                ('genres', models.CharField(max_length=300)),
                ('runtime', models.IntegerField()),
                ('similar_movies', models.CharField(max_length=500)),
            ],
        ),
    ]
