# Generated by Django 5.1.3 on 2024-11-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='similar_movies',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
