# Generated by Django 5.1.3 on 2024-11-10 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0002_alter_movie_similar_movies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='similar_movies',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
